#!/bin/bash
# this is a simple bash script for automated installation of Bookstore
echo Bookstore: installing required packages..
echo Installing backend packages
cd backend && npm install
cd ..
echo Installing frontend packages
cd frontend && npm install
echo Done! Run 'npm start' to run project!